spring.application.name=shardedSagaWallet
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.url=jdbc:shardingsphere:classpath:sharding.yml
spring.datasource.driver-class-name=org.apache.shardingsphere.driver.ShardingSphereDriver